//
//  DamageRateInfo.swift
//
//
//  Created by Christopher Engelbart on 12/21/23.
//

import Foundation

enum DamageRateInfo: String, Codable {
    case blaster = "Blaster"
    case blasterKillOneShot = "Blaster_KillOneShot"
    case blasterMiddle = "Blaster_BlasterMiddle"
    case blasterShort = "Blaster_BlasterShort"
    case blowerExhale = "BlowerExhale"
    case blowerExhaleBombCore = "BlowerExhale_BombCore"
    case blowerInhale = "BlowerInhale"
    case bomb = "Bomb"
    case bombCurlingBullet = "Bomb_CurlingBullet"
    case bombDirectHit = "Bomb_DirectHit"
    case bombFizzy = "Bomb_Fizzy"
    case bombSuction = "Bomb_Suction"
    case bombTorpedoBullet = "Bomb_TorpedoBullet"
    case bombTorpedoSplashBurst = "Bomb_TorpedoSplashBurst"
    case bombTrap = "Bomb_Trap"
    case brushCore = "BrushCore"
    case brushSplash = "BrushSplash"
    case castle = "Castle"
    case charger = "Charger"
    case chargerFull = "ChargerFull"
    case chargerFullLight = "ChargerFull_Light"
    case chargerFullLong = "ChargerFull_Long"
    case chargerLight = "Charger_Light"
    case chargerLong = "Charger_Long"
    case chariotBody = "Chariot_Body"
    case chariotCannon = "Chariot_Cannon"
    case chimney = "Chimney"
    case `default` = "Default"
    case gachihokoBullet = "Gachihoko_Bullet"
    case gachihokoBombCore = "Gachihoko_BombCore"
    case inkStorm = "InkStorm"
    case inkStormRain = "InkStormRain"
    case jetpackBullet = "Jetpack_Bullet"
    case jetpackBombCore = "Jetpack_BombCore"
    case jetpackCoop = "Jetpack_Coop"
    case jetpackJet = "Jetpack_Jet"
    case maneuver = "Maneuver"
    case maneuverShort = "Maneuver_Short"
    case microLaser = "MicroLaser"
    case multiMissileBullet = "MultiMissile_Bullet"
    case multiMissileBombCore = "MultiMissile_BombCore"
    case niceBall = "NiceBall"
    case pogo = "Pogo"
    case rollerCore = "RollerCore"
    case rollerSplash = "RollerSplash"
    case rollerSplashCompact = "RollerSplash_Compact"
    case rollerSplashHeavy = "RollerSplash_Heavy"
    case rollerSplashHunter = "RollerSplash_Hunter"
    case rollerSplashWide = "RollerSplash_Wide"
    case saber = "Saber"
    case saberChargeShot = "Saber_ChargeShot"
    case saberChargeSlash = "Saber_ChargeSlash"
    case saberChargeSlashPenetrate = "Saber_ChargeSlash_Penetrate"
    case saberShot = "Saber_Shot"
    case saberSlash = "Saber_Slash"
    case shelter = "Shelter"
    case shelterCanopy = "ShelterCanopy"
    case shelterCanopyCompact = "ShelterCanopy_Compact"
    case shelterCanopyWide = "ShelterCanopy_Wide"
    case shelterShot = "ShelterShot"
    case shelterShotCompact = "ShelterShot_Compact"
    case shelterShotWide = "ShelterShot_Wide"
    case shield = "Shield"
    case shockSonarWave = "ShockSonar_Wave"
    case shooter = "Shooter"
    case shooterBlaze = "Shooter_Blaze"
    case shooterExpert = "Shooter_Expert"
    case shooterFlash = "Shooter_Flash"
    case shooterFlashRepeat = "Shooter_FlashRepeat"
    case shooterFirst = "Shooter_First"
    case shooterGravity = "Shooter_Gravity"
    case shooterHeavy = "Shooter_Heavy"
    case shooterLong = "Shooter_Long"
    case shooterPrecision = "Shooter_Precision"
    case shooterShort = "Shooter_Short"
    case shooterTripleMiddle = "Shooter_TripleMiddle"
    case shooterTripleQuick = "Shooter_TripleQuick"
    case skewer = "Skewer"
    case skewerBody = "Skewer_Body"
    case slosher = "Slosher"
    case slosherBathtub = "Slosher_Bathtub"
    case slosherBear = "Slosher_Bear"
    case slosherWashtub = "Slosher_Washtub"
    case slosherWashtubBombCore = "Slosher_WashtubBombCore"
    case spinner = "Spinner"
    case sprinkler = "Sprinkler"
    case stringer = "Stringer"
    case stringerShort = "Stringer_Short"
    case superHook = "SuperHook"
    case superLanding = "SuperLanding"
    case tripleTornado = "TripleTornado"
    case ultraShot = "UltraShot"
    case ultraStampThrow = "UltraStamp_Throw"
    case ultraStampSwing = "UltraStamp_Swing"
    case ultraStampThrowBombCore = "UltraStamp_Throw_BombCore"
}
