//
//  ColumnKey.swift
//
//
//  Created by Christopher Engelbart on 12/21/23.
//

import Foundation

enum ColumnKey: String, Codable {
    case attractTarget = "AttractTarget"
    case blowerInhale = "BlowerInhale"
    case blowoutsRoll = "BlowoutsRoll"
    case bombTorpedoBullet = "Bomb_TorpedoBullet"
    case bulletPogo = "BulletPogo"
    case bulletUmbrellaCanopyCompact = "BulletUmbrellaCanopyCompact"
    case bulletUmbrellaCanopyNormal = "BulletUmbrellaCanopyNormal"
    case bulletUmbrellaCanopyWide = "BulletUmbrellaCanopyWide"
    case castleKnockBack = "CastleKnockBack"
    case chariot = "Chariot"
    case coopEnemyCupTwinsCup = "CoopEnemyCupTwinsCup"
    case coopEnemyFriendlyFire = "CoopEnemyFriendlyFire"
    case coopEnemyHardBody = "CoopEnemyHardBody"
    case coopEnemySakeJaw = "CoopEnemySakeJaw"
    case coopEnemySakeRope = "CoopEnemySakeRope"
    case coopEnemySakeTamaire = "CoopEnemySakeTamaire"
    case coopEnemySakeTamaireOneBomb = "CoopEnemySakeTamaireOneBomb"
    case coopEnemySakelienCupTwins = "CoopEnemySakelienCupTwins"
    case coopEnemySakelienGiant = "CoopEnemySakelienGiant"
    case coopEnemySakelienGiantFriendlyFire = "CoopEnemySakelienGiantFriendlyFire"
    case coopEnemySakelienTowerPart = "CoopEnemySakelienTowerPart"
    case coopEnemySakelienTowerUnite = "CoopEnemySakelienTowerUnite"
    case coopGoldenIkuraBox = "CoopGoldenIkuraBox"
    case coopPropeller = "CoopPropeller"
    case coopSpawnBox = "CoopSpawnBox"
    case decoy = "Decoy"
    case `default` = "Default"
    case enemyRockBall = "EnemyRockBall"
    case gachihokoBarrier = "Gachihoko_Barrier"
    case geyserOnline = "GeyserOnline"
    case greatBarrierBarrier = "GreatBarrier_Barrier"
    case greatBarrierWeakPoint = "GreatBarrier_WeakPoint"
    case inkRail = "InkRail"
    case msnBossWeak = "MsnBossWeak"
    case msnBossHard = "MsnBoxHard"
    case msnBoxL = "MsnBoxL"
    case msnBoxS = "MsnBoxS"
    case msnEnemy = "MsnEnemy"
    case msnEnemyEscape = "MsnEnemyEscape"
    case msnEnemyShield = "MsnEnemyShield"
    case msnEnemyTakopodDEV = "MsnEnemyTakopodDEV"
    case msnGoal = "MsnGoal"
    case msnLeaderMoray = "MsnLeaderMoray"
    case msnMantaShadow = "MsnMantaShadow"
    case msnRailKingHand = "MsnRailKingHand"
    case msnSharkKing = "MsnSharkKing"
    case msnYakan = "MsnYakan"
    case niceBallArmor = "NiceBall_Armor"
    case propeller = "Propeller"
    case propellerOnline = "PropellerOnline"
    case salmonBuddy = "SalmonBuddy"
    case shockSonar = "ShockSonar"
    case snakeBlock = "SnakeBlock"
    case spongeVersus = "Sponge_Versus"
    case wsbFlag = "Wsb_Flag"
    case wsbShield = "Wsb_Shield"
    case wsbSprinkler = "Wsb_Sprinkler"
}
