name: Deploy Documentation

on:
  workflow_run:
    workflows: ["Swift"]
    branches: ["main"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-26

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.5'

      - name: Create Staging Directory
        run: mkdir -p ./.build/github-pages

      - name: Generate Docs
        run: |
          swift --version
          swift package --allow-writing-to-directory ./.build/github-pages generate-documentation --enable-experimental-combined-documentation --target Splatalyzer --target SplatalyzerUI --target SplatalyzerUpdater --disable-indexing --transform-for-static-hosting --hosting-base-path Splatalyzer --output-path ./.build/github-pages

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.build/github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
