# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0-beta'
    - name: Build
      run: xcodebuild build-for-testing -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -verbose | xcpretty
    - name: General Tests
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan 'Splatalyzer-Package' -verbose
    - name: Tests for English
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'English-US' -verbose
    - name: Tests for Chinese (CN/Simplified)
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Chinese-CN-Simplified' -verbose 
    - name: Tests for Chinese (TW/Traditional)
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Chinese-TW-Traditional' -verbose
    - name: Tests for Dutch
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Dutch' -verbose
    - name: Tests for French (Canada)
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'French-CA' -verbose
    - name: Tests for French (France)
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'French-FR' -verbose
    - name: Tests for German
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'German' -verbose
    - name: Tests for Italian
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Italian' -verbose
    - name: Tests for Japanese
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Japanese' -verbose
    - name: Tests for Russian
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Russian' -verbose
    - name: Tests for Spanish (Spain)
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Spanish-ES' -verbose
    - name: Tests for Spanish (Latin America)
      run: xcodebuild test-without-building -scheme Splatalyzer-Package -destination 'platform=macOS,arch=arm64' -testPlan Localization -only-test-configuration 'Spanish-LA' -verbose
