# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme Splatalyzer-Package -destination 'platform=macOS,arch=x86_64' -verbose | xcpretty
    - name: General Tests
      run: xcodebuild -scheme Splatalyzer-Package -destination 'platform=macOS,arch=x86_64' -testPlan 'Splatalyzer-Package' -verbose test | xcpretty
    - name: Tests for English
      run: xcodebuild -scheme Splatalyzer-Package -destination 'platform=macOS,arch=x86_64' -testPlan Localization -only-test-configuration 'English-US' -verbose test | xcpretty
